property:
  type: dev
  
server:
  port: 9010
  shutdown: graceful
  
logging:
  level:
    '[org.springframework]': debug
    '[org.springframework.web]': debug
    
spring:
  datasource:
    data:
     jdbc:oracle:thin:@localhost:1521:xe
    username: user
    password: pw
    driver-class-name:
      oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    
solace:
  java:
    host: 52.79.64.176:55555
    msg-vpn: default
    client-username: default
    client-password: 
    client-name: MOS-File-Interface-System
    reconnnect-retries: 5
    retries-per-host: 5
    module-name: test

    
nas:
  sftp: 
    host: 
    port: 
    user-name:
    user-passwd: 
    remote-target-dir: 