property:
  type: dev
  
server:
  port: 9010
  shutdown: graceful
  
logging:
  level:
    '[org.springframework]': debug
    '[org.springframework.web]': debug
    
spring:
  datasource:
    url: jdbc:oracle:thin:@mes-oracle.crhbirj6sm35.ap-northeast-2.rds.amazonaws.com:1522:ORCL
    username: mesadm
    password: absolics12#
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_create: true
        dialect: org.hibernate.dialect.Oracle12cDialect
    
solace:
  java:
    host: 52.79.64.176:55555
    msg-vpn: MES
    client-username: default
    client-password: admin
    client-name: MOS-File-Interface-System
    reconnnect-retries: 20
    retries-per-host: 5
    reconnect-retry-wait: 3000 ms
    module-name: test
    
    
nas:
  sftp: 
    host: 
    port: 
    user-name:
    user-passwd: 
    remote-target-dir: 
   

psd:
  url: jdbc:oracle:thin:@0.0.0.0:1522:ORCL
  username: sys
  password: 
  