property:
  type: dev

server:
#  port: 9010
  port: 8008
  shutdown: graceful


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate : debug
#    '[org.springframework]': debug
#    '[org.springframework.web]': debug
   

spring:
  boot:
    antoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration    
  datasource:
    url: jdbc:oracle:thin:@mes-oracle.crhbirj6sm35.ap-northeast-2.rds.amazonaws.com:1522:ORCL
#    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: mesadm
    password: absolics12#
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 100
#        dialect: org.hibernate.dialect.Oracle12cDialect\
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
  transaction:
    mode: jdbc


#Solace 접속 정보            


#SFTP (NAS 접속 정보)    
nas:
  sftp: 
    host: 192.168.0.193
    port: 22
    user-name: mestest
    user-passwd: absadmin
    remote-target-dir:  ./backup/

##### Application Config ####
ap:
  info:
    group: FIS
    site: SVM
    env: DEV
    sequence: 1
  file:
    mode: local
    nas:
      sftp:
        host: 192.168.0.193
        port: 22
        user-name: mestest
        user-passwd: absadmin
        remote-target-dir: ./backup/
    local-path: D:\\parsingfile.csv
    
  interface:
    solace:
      host: 52.79.64.176:55555
#      host: localhost:55555
      vpn: MES
      client:
        username: default
        password: admin
      connect:
        trial-count: 2
      reconnect:
        trial-count: 20
        per-host: 5
    destination:
      send:
        topic: SVM/DEV/EDC/CMN/00
      receive:
        queue: SVM_DEV_FIS_CMN
        init: SVM/DEV/FIS/CMN/INIT
       
  query:
    parsing:
      Inpection: INSERT INTO CN_FIS_EDC_TMP(WORK_ID,FILE_SPC,ROW_SEQ,FILE_TP,SITE_ID,PROD_DEF_ID,PROC_DEF_ID,PROC_SGMT_ID,EQP_ID,LOT_ID,PROD_MTRL_ID,SUB_PROD_MTRL_ID,MTRL_FACE_CD,INSP_REPT_CNT,X_VAL,Y_VAL,GRD_ID,DFCT_ID,DFCT_X_VAL,DFCT_Y_VAL,INSP_DT,IMG_FILE_NM,REVIEW_IMG_FILE_NM,INSP_FILE_NM,ATTR_1,ATTR_2,ATTR_N)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
      Measure: INSERT INTO CN_FIS_EDC_TMP(WORK_ID,FILE_SPC,ROW_SEQ,FILE_TP,SITE_ID,PROD_DEF_ID,PROC_DEF_ID,PROC_SGMT_ID,EQP_ID,LOT_ID,PROD_MTRL_ID,MTRL_FACE_CD,INSP_REPT_CNT,X_VAL,Y_VAL,Z_VAL,DCITEM_ID,RSLT_VAL)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
      rollback: DELETE FROM CN_FIS_EDC_TMP WHERE WORK_ID = ?      
    rule:
      parsing: SELECT EQP_NM,FILE_FM_TP,FILE_TP,TG_FILE_MV_PT,PRS_TTL_INFO,PRS_ROW_INFO FROM CN_FIS_IF_PARSING_FILE_INFO
      mapping: SELECT EQP_NM,FILE_FM_TP,FILE_TP,FILE_COLM_NUM,FILE_CLM_INFO,MPP_CLM_INFO FROM CN_FIS_IF_PARSING_DATA_MAPPING_INFO
