-- MESADM.CN_FIS_MEAS_DATA definition

CREATE TABLE "MESADM"."CN_FIS_MEAS_DATA"
(	"OBJ_ID" VARCHAR2(100) DEFAULT NULL NOT NULL ENABLE,
     "FILE_POSN_VAL" VARCHAR2(255),
     "FILE_NM" VARCHAR2(255) NOT NULL ENABLE,
     "WORK_ID" VARCHAR2(255) NOT NULL ENABLE,
     "ROW_SEQ" NUMBER(38,0) NOT NULL ENABLE,
     "SITE_ID" VARCHAR2(40),
     "PROD_DEF_ID" VARCHAR2(40),
     "PROC_DEF_ID" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "PROD_MTRL_ID" VARCHAR2(40),
     "MTRL_FACE_CD" VARCHAR2(40),
     "REPT_CNT" NUMBER(38,0),
     "X_VAL" NUMBER(38,0),
     "Y_VAL" NUMBER(38,0),
     "Z_VAL" NUMBER(38,0),
     "DCITEM_ID" VARCHAR2(40),
     "RSLT_VAL" VARCHAR2(40),
     "IMG_FILE_NM" VARCHAR2(255),
     "INSP_FILE_NM" VARCHAR2(255),
     "ATTR_1" VARCHAR2(40),
     "ATTR_2" VARCHAR2(255),
     "ATTR_N" VARCHAR2(255),
     "CRT_DT" TIMESTAMP (6) NOT NULL ENABLE,
     "CRT_USER_ID" VARCHAR2(40) DEFAULT 'FIS',
     CONSTRAINT "CN_FIS_MEAS_DATA_PK" PRIMARY KEY ("OBJ_ID")

);

COMMENT ON TABLE MESADM.CN_FIS_MEAS_DATA IS '계측 파싱 데이터';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.OBJ_ID IS '오브젝트 ID';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.FILE_POSN_VAL IS '파일 위치 값';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.FILE_NM IS '파일 이름';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.WORK_ID IS '워크ID';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.ROW_SEQ IS '로우 번호';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.SITE_ID IS '라인 정보';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.PROD_DEF_ID IS '제품 코드';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.PROC_DEF_ID IS 'Process Flow';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.PROC_SGMT_ID IS '공정 코드';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.EQP_ID IS '설비ID';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.PROD_MTRL_ID IS 'Panel ID';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.MTRL_FACE_CD IS '계측 작업면';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.REPT_CNT IS '계측 반복 회차';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.X_VAL IS 'Panel X위치';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.Y_VAL IS 'Panel Y위치';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.Z_VAL IS 'Panel Z위치';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.DCITEM_ID IS '계측 항목';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.RSLT_VAL IS '계측 결과';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.IMG_FILE_NM IS '계측 이미지 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.INSP_FILE_NM IS '결과 데이터 원본 파일';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.ATTR_1 IS '특화 추가 속성1';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.ATTR_2 IS '특화 추가 속성2';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.ATTR_N IS '특화 추가 속성N';
COMMENT ON COLUMN MESADM.CN_FIS_MEAS_DATA.CRT_DT IS '생성 일시';