-- MESADM.CN_FIS_INSP_DATA definition

CREATE TABLE "MESADM"."CN_FIS_INSP_DATA"
(	"OBJ_ID" VARCHAR2(100) DEFAULT NULL NOT NULL ENABLE,
     "FILE_POSN_VAL" VARCHAR2(255),
     "FILE_NM" VARCHAR2(255) NOT NULL ENABLE,
     "WORK_ID" VARCHAR2(255) NOT NULL ENABLE,
     "ROW_SEQ" NUMBER(38,0) NOT NULL ENABLE,
     "SITE_ID" VARCHAR2(40),
     "PROD_DEF_ID" VARCHAR2(40),
     "PROC_DEF_ID" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "PROD_MTRL_ID" VARCHAR2(40),
     "SUB_PROD_MTRL_ID" VARCHAR2(40),
     "MTRL_FACE_CD" VARCHAR2(40),
     "INSP_REPT_CNT" NUMBER(38,0),
     "X_VAL" NUMBER(38,0),
     "Y_VAL" NUMBER(38,0),
     "GRD_ID" VARCHAR2(40),
     "DFCT_ID" VARCHAR2(40),
     "INSP_DT" TIMESTAMP (6),
     "IMG_FILE_NM" VARCHAR2(255),
     "REVIEW_IMG_FILE_NM" VARCHAR2(255),
     "INSP_FILE_NM" VARCHAR2(255),
     "ATTR_1" VARCHAR2(40),
     "ATTR_2" VARCHAR2(40),
     "ATTR_N" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6) NOT NULL ENABLE,
     CONSTRAINT "CN_FIS_INSP_DATA_PK" PRIMARY KEY ("OBJ_ID")
);

COMMENT ON TABLE MESADM.CN_FIS_INSP_DATA IS '검사 파싱 데이터';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.OBJ_ID IS '오브젝트 ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.FILE_POSN_VAL IS '파일 위치 값';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.FILE_NM IS '파일 이름';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.WORK_ID IS '워크 ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.ROW_SEQ IS '파싱 로우';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.SITE_ID IS '라인 정보';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.PROD_DEF_ID IS '제품 코드';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.PROC_DEF_ID IS 'Process Flow';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.PROC_SGMT_ID IS '공정 코드';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.EQP_ID IS '설비 ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.PROD_MTRL_ID IS 'Panel ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.SUB_PROD_MTRL_ID IS '하위 제품 ID';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.MTRL_FACE_CD IS '검사 작업 면';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.INSP_REPT_CNT IS '검사 반복 회차';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.X_VAL IS 'Panel X 좌표';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.Y_VAL IS 'Panel Y 좌표';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.GRD_ID IS '등급 코드';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.DFCT_ID IS 'DEFECT CODE';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.INSP_DT IS '검사시간';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.IMG_FILE_NM IS '불량 이미지 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.REVIEW_IMG_FILE_NM IS '불량 이미지 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.INSP_FILE_NM IS '검사 데이터 원본 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.ATTR_1 IS '특화 추가 속성1';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.ATTR_2 IS '특화 추가 속성2';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.ATTR_N IS '특화 추가 속성N';
COMMENT ON COLUMN MESADM.CN_FIS_INSP_DATA.CRT_DT IS '생성 일시';