-- MESADM.CN_FIS_PARSE_RULE_REL definition

CREATE TABLE "MESADM"."CN_FIS_PARSE_RULE_REL"
(	"OBJ_ID" VARCHAR2(100) NOT NULL ENABLE,
     "EQP_ID" VARCHAR2(40) NOT NULL ENABLE,
     "FILE_TYP" VARCHAR2(40) NOT NULL ENABLE,
     "FILE_CLM_VAL" VARCHAR2(40),
     "FILE_CLM_NM" VARCHAR2(40) NOT NULL ENABLE,
     "MPNG_CLM_NM" VARCHAR2(40) NOT NULL ENABLE,
     "CLM_DATA_TYP" VARCHAR2(100),
     "CRT_DT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "CRT_USER_ID" VARCHAR2(40) DEFAULT 'FIS' NOT NULL ENABLE,
     "MDFY_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40) DEFAULT SYSTIMESTAMP,
     CONSTRAINT "CN_FIS_PARSE_RULE_REL_PK" PRIMARY KEY ("OBJ_ID"),
     CONSTRAINT "CN_FIS_PARSE_RULE_REL_UK" UNIQUE ("EQP_ID","FILE_TYP","FILE_CLM_VAL")

);

COMMENT ON TABLE MESADM.CN_FIS_PARSE_RULE_REL IS '파싱 데이터의 매핑 컬럼 정보 테이블';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.OBJ_ID IS '매핑정보시퀀스ID';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.EQP_ID IS '장비이름';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.FILE_TYP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.FILE_CLM_VAL IS '파일컬럼값';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.FILE_CLM_NM IS '파일컬럼이름';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.MPNG_CLM_NM IS '매핑컬럼이름';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.CLM_DATA_TYP IS '컬럼 데이터 타입';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.CRT_USER_ID IS '생성자아이디';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.MDFY_DT IS '수정일시';
COMMENT ON COLUMN MESADM.CN_FIS_PARSE_RULE_REL.MDFY_USER_ID IS '수정자아이디';