
------------------------------------------------------------초기 생성 Query - 20231027
-- MESADM.CN_FIS_IF_PARSING_FILE_INFO definition
CREATE TABLE MESADM.CN_FIS_IF_PARSING_FILE_INFO (
	PS_SEQ NUMBER NOT NULL,
	EQP_NM VARCHAR2(100) NOT NULL,
	FILE_FM_TP CHAR(1) NOT NULL,
	FILE_TP VARCHAR2(10) NOT NULL,
	DF_FILE_PT VARCHAR2(100) NOT NULL,
	FILE_CLM_INFO VARCHAR2(200) NOT NULL,
	PS_ROW_INFO VARCHAR2(200) NOT NULL,
	CRT_DT TIMESTAMP NOT NULL,
	CRTR VARCHAR2(20) NOT NULL,
	MDFT_DT TIMESTAMP NULL,
	MDFTR VARCHAR2(20) NULL,	
	CONSTRAINT IF_PARSING_FILE_INFO_PK PRIMARY KEY (PS_SEQ)
);
CREATE INDEX CN_FIS_IF_PARSING_FILE_INFO_EQP_NM_IDX ON MESADM.CN_FIS_IF_PARSING_FILE_INFO (EQP_NM,FILE_FM_TP,FILE_TP);
COMMENT ON TABLE MESADM.CN_FIS_IF_PARSING_FILE_INFO IS '파싱 파일 정보 보관 테이블';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.PS_SEQ IS '순번';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.EQP_NM IS '설비명';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_FM_TP IS '파일포맷유형';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_TP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.DF_FILE_PT IS '기본파일위치';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_CLM_INFO IS '파싱컬럼정보';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.PS_ROW_INFO IS '파싱행정보';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.CRT_DT IS '입력일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.CRTR IS '입력자';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.MDFT_DT IS '수정일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.MDFTR IS '수정자';


-- MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO definition
CREATE TABLE MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO (
	PM_SEQ NUMBER NOT NULL,
	EQP_NM VARCHAR2(100) NOT NULL,
	FILE_TP VARCHAR2(100) NOT NULL,
	FILE_CLM_INFO VARCHAR2(100) NOT NULL,
	MPP_CLM_INFO VARCHAR2(100) NOT NULL,
	CRT_DT VARCHAR2(100) NOT NULL,
	CRTR VARCHAR2(100) NOT NULL,
	MDFT_DT VARCHAR2(100) NULL,
	MDFTR VARCHAR2(100) NULL,
	CONSTRAINT IF_PARSING_DATA_MAPPING_PK PRIMARY KEY (PM_SEQ)
);
CREATE INDEX CN_FIS_IF_PARSING_DATA_MAPPING_INFO_EQP_NM_IDX ON MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO (EQP_NM,FILE_TP,FILE_CLM_INFO);
COMMENT ON TABLE MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO IS '파싱 데이터의 매핑 컬럼 정보 테이블';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.PM_SEQ IS '순번';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.EQP_NM IS '설비명';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.FILE_TP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.FILE_CLM_INFO IS '파싱 컬럼명';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.MPP_CLM_INFO IS '맵핑 컬럼명';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.CRT_DT IS '입력일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.CRTR IS '입력자';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.MDFT_DT IS '수정일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO.MDFTR IS '수정자';


-- MESADM.CN_FIS_EDC_TMP definition
CREATE TABLE MESADM.CN_FIS_EDC_TMP (
	PD_SEQ NUMBER(38,0) NOT NULL,
	FILE_TP VARCHAR2(100) NULL,	
	FILE_FM_TP VARCHAR2(100) NULL,
	SITE_ID VARCHAR2(100) NULL,
	PROD_DEF_ID VARCHAR2(100) NULL,
	PROC_DEF_ID VARCHAR2(100) NULL,
	PROC_SGMT_ID VARCHAR2(100) NULL,
	EQP_ID VARCHAR2(100) NULL,
	LOT_ID VARCHAR2(100) NULL,
	PROD_MTRL_ID VARCHAR2(100) NULL,
	SUB_PROD_MTRL_ID VARCHAR2(100) NULL,
	MTRL_FACE_CD VARCHAR2(100) NULL,
	INSP_REPT_CNT VARCHAR2(100) NULL,
	X_VAL VARCHAR2(100) NULL,
	Y_VAL VARCHAR2(100) NULL,
	Z_VAL VARCHAR2(100) NULL,
	DCITEM_ID VARCHAR2(100) NULL,
	RSLT_VAL VARCHAR2(100) NULL,
	GRD_ID VARCHAR2(100) NULL,
	DFCT_ID VARCHAR2(100) NULL,
	DFCT_X_VAL VARCHAR2(100) NULL,
	DFCT_Y_VAL VARCHAR2(100) NULL,
	INSP_DT VARCHAR2(100) NULL,
	IMG_FILE_NM VARCHAR2(100) NULL,
	REVIEW_IMG_FILE_NM VARCHAR2(100) NULL,
	INSP_FILE_NM VARCHAR2(100) NULL,
	ATTR_1 VARCHAR2(100) NULL,
	ATTR_2 VARCHAR2(100) NULL,
	ATTR_N VARCHAR2(100) NULL,
	CRT_DT TIMESTAMP NOT NULL,
	PRCS_STATE CHAR(1) NULL,
	CONSTRAINT CN_FIS_EDC_TMP_PK PRIMARY KEY (PD_SEQ)
);
COMMENT ON TABLE MESADM.CN_FIS_EDC_TMP IS '파싱 데이터 임시 저장';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.FILE_TP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PD_SEQ IS '순번';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.FILE_FM_TP IS '파일포멧유형';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.SITE_ID IS '라인정보';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROD_DEF_ID IS '제품코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROC_DEF_ID IS '프로세스 플로우';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROC_SGMT_ID IS '공정코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.EQP_ID IS '설비ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROD_MTRL_ID IS 'Panel ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.SUB_PROD_MTRL_ID IS '하위 제품 ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.MTRL_FACE_CD IS '검사 작업면';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_REPT_CNT IS '검사 반복 회차';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.X_VAL IS 'Unit의 Paanel 내 X좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.Y_VAL IS 'Unit의 Paanel 내 Y좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.Z_VAL IS 'Unit의 Paanel 내 Z좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DCITEM_ID IS '계측 항목';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.RSLT_VAL IS '계측 결과';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.GRD_ID IS '등급 코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_ID IS 'DEFECT CODE';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_X_VAL IS 'Deefect Point X좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_Y_VAL IS 'Deefect Point Y좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_DT IS '검사 시간';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.IMG_FILE_NM IS '불량/계측 이미지 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.REVIEW_IMG_FILE_NM IS '불량 이미지 경로 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_FILE_NM IS '검사/결과 데이터 원본 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_1 IS '검사 공정/설비별 특화 추가 속성1';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_2 IS '검사 공정/설비별 특화 추가 속성2';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_N IS '검사 공정/설비별 특화 추가 속성 N';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_N IS '입력일시';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_N IS '처리상태';






------------------------------------------------------------ table DDL

-- MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO definition

CREATE TABLE "MESADM"."CN_FIS_IF_PARSING_DATA_MAPPING_INFO" 
   (	"PM_SEQ" NUMBER NOT NULL ENABLE, 
	"EQP_NM" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_TP" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_CLM_INFO" VARCHAR2(100) NOT NULL ENABLE, 
	"MPP_CLM_INFO" VARCHAR2(100) NOT NULL ENABLE, 
	"CRT_DT" VARCHAR2(100) NOT NULL ENABLE, 
	"CRTR" VARCHAR2(100) NOT NULL ENABLE, 
	"MDFT_DT" VARCHAR2(100), 
	"MDFTR" VARCHAR2(100), 
	 CONSTRAINT "IF_PARSING_DATA_MAPPING_PK" PRIMARY KEY ("PM_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."IF_PARSING_DATA_MAPPING_PK" ON "MESADM"."CN_FIS_IF_PARSING_DATA_MAPPING_INFO" ("PM_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;
  CREATE INDEX "MESADM"."CN_FIS_IF_PARSING_DATA_MAPPING_INFO_EQP_NM_IDX" ON "MESADM"."CN_FIS_IF_PARSING_DATA_MAPPING_INFO" ("EQP_NM", "FILE_TP", "FILE_CLM_INFO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

COMMENT ON TABLE MESADM.CN_FIS_IF_PARSING_DATA_MAPPING_INFO IS '파싱 데이터의 매핑 컬럼 정보 테이블';




-- MESADM.CN_FIS_IF_PARSING_FILE_INFO definition

CREATE TABLE "MESADM"."CN_FIS_IF_PARSING_FILE_INFO" 
   (	"PS_SEQ" NUMBER NOT NULL ENABLE, 
	"EQP_NM" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_FM_TP" CHAR(1) NOT NULL ENABLE, 
	"FILE_TP" VARCHAR2(10) NOT NULL ENABLE, 
	"DF_FILE_PT" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_CLM_INFO" VARCHAR2(200) NOT NULL ENABLE, 
	"PS_ROW_INFO" VARCHAR2(200) NOT NULL ENABLE, 
	"CRT_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"CRTR" VARCHAR2(20) NOT NULL ENABLE, 
	"MDFT_DT" TIMESTAMP (6), 
	"MDFTR" VARCHAR2(20), 
	 CONSTRAINT "IF_PARSING_FILE_INFO_PK" PRIMARY KEY ("PS_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."IF_PARSING_FILE_INFO_PK" ON "MESADM"."CN_FIS_IF_PARSING_FILE_INFO" ("PS_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;
  CREATE INDEX "MESADM"."CN_FIS_IF_PARSING_FILE_INFO_EQP_NM_IDX" ON "MESADM"."CN_FIS_IF_PARSING_FILE_INFO" ("EQP_NM", "FILE_FM_TP", "FILE_TP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

COMMENT ON TABLE MESADM.CN_FIS_IF_PARSING_FILE_INFO IS '파싱 파일 정보 보관 테이블';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.PS_SEQ IS '순번';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.EQP_NM IS '설비명';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_FM_TP IS '파일포맷유형';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_TP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.DF_FILE_PT IS '기본파일위치';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.FILE_CLM_INFO IS '파싱컬럼정보';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.PS_ROW_INFO IS '파싱행정보';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.CRT_DT IS '입력일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.CRTR IS '입력자';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.MDFT_DT IS '수정일시';
COMMENT ON COLUMN MESADM.CN_FIS_IF_PARSING_FILE_INFO.MDFTR IS '수정자';





-- MESADM.CN_FIS_EDC_TMP definition

CREATE TABLE "MESADM"."CN_FIS_EDC_TMP" 
   (	"PD_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"FILE_TP" VARCHAR2(100), 
	"FILE_FM_TP" VARCHAR2(100), 
	"SITE_ID" VARCHAR2(100), 
	"PROD_DEF_ID" VARCHAR2(100), 
	"PROC_DEF_ID" VARCHAR2(100), 
	"PROC_SGMT_ID" VARCHAR2(100), 
	"EQP_ID" VARCHAR2(100), 
	"LOT_ID" VARCHAR2(100), 
	"PROD_MTRL_ID" VARCHAR2(100), 
	"SUB_PROD_MTRL_ID" VARCHAR2(100), 
	"MTRL_FACE_CD" VARCHAR2(100), 
	"INSP_REPT_CNT" VARCHAR2(100), 
	"X_VAL" VARCHAR2(100), 
	"Y_VAL" VARCHAR2(100), 
	"Z_VAL" VARCHAR2(100), 
	"DCITEM_ID" VARCHAR2(100), 
	"RSLT_VAL" VARCHAR2(100), 
	"GRD_ID" VARCHAR2(100), 
	"DFCT_ID" VARCHAR2(100), 
	"DFCT_X_VAL" VARCHAR2(100), 
	"DFCT_Y_VAL" VARCHAR2(100), 
	"INSP_DT" VARCHAR2(100), 
	"IMG_FILE_NM" VARCHAR2(100), 
	"REVIEW_IMG_FILE_NM" VARCHAR2(100), 
	"INSP_FILE_NM" VARCHAR2(100), 
	"ATTR_1" VARCHAR2(100), 
	"ATTR_2" VARCHAR2(100), 
	"ATTR_N" VARCHAR2(100), 
	"CRT_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"PRCS_STATE" CHAR(1), 
	 CONSTRAINT "CN_FIS_EDC_TMP_PK" PRIMARY KEY ("PD_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."CN_FIS_EDC_TMP_PK" ON "MESADM"."CN_FIS_EDC_TMP" ("PD_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

COMMENT ON TABLE MESADM.CN_FIS_EDC_TMP IS '파싱 데이터 임시 저장';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PD_SEQ IS '순번';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.FILE_TP IS '파일유형';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.FILE_FM_TP IS '파일포멧유형';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.SITE_ID IS '라인정보';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROD_DEF_ID IS '제품코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROC_DEF_ID IS '프로세스 플로우';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROC_SGMT_ID IS '공정코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.EQP_ID IS '설비ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.PROD_MTRL_ID IS 'Panel ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.SUB_PROD_MTRL_ID IS '하위 제품 ID';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.MTRL_FACE_CD IS '검사 작업면';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_REPT_CNT IS '검사 반복 회차';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.X_VAL IS 'Unit의 Paanel 내 X좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.Y_VAL IS 'Unit의 Paanel 내 Y좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.Z_VAL IS 'Unit의 Paanel 내 Z좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DCITEM_ID IS '계측 항목';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.RSLT_VAL IS '계측 결과';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.GRD_ID IS '등급 코드';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_ID IS 'DEFECT CODE';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_X_VAL IS 'Deefect Point X좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.DFCT_Y_VAL IS 'Deefect Point Y좌표';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_DT IS '검사 시간';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.IMG_FILE_NM IS '불량/계측 이미지 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.REVIEW_IMG_FILE_NM IS '불량 이미지 경로 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.INSP_FILE_NM IS '검사/결과 데이터 원본 파일명';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_1 IS '검사 공정/설비별 특화 추가 속성1';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_2 IS '검사 공정/설비별 특화 추가 속성2';
COMMENT ON COLUMN MESADM.CN_FIS_EDC_TMP.ATTR_N IS '처리상태';




-- MESADM.CN_FIS_EDC_TMP InspectData BATCH INSERT SQL

INSERT INTO CN_FIS_EDM_TMP(	
	SITE_ID,
	PROD_DEF_ID,
	PROC_DEF_ID,
	PROC_SGMT_ID,
	EQP_ID,
	LOT_ID,
	PROD_MTRL_ID,
	SUB_PROD_MTRL_ID,
	MTRL_FACE_CD,
	INSP_REPT_CNT,
	X_VAL,
	Y_VAL,
	GRD_ID,
	DFCT_ID,
	DFCT_X_VAL,
	DFCT_Y_VAL,
	INSP_DT,
	IMG_FILE_NM,
	REVIEW_IMG_FILE_NM,
	INSP_FILE_NM,
	ATTR_1,
	ATTR_2,
	ATTR_N,
	CRT_DT,
	FILE_NM
) VALUES (
	?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTEMP,?
)


-- MESADM.CN_FIS_EDC_TMP Instrumentsation BATCH INSERT SQL
INSERT INTO CN_FIS_EDM_TMP(
	SITE_ID,
	PROD_DEF_ID,
	PROC_DEF_ID,
	PROC_SGMT_ID,
	EQP_ID,
	LOT_ID,
	PROD_MTRL_ID,
	MTRL_FACE_CD,
	INSP_REPT_CNT,
	X_VAL,
	Y_VAL,
	Z_VAL,
	DCITEM_ID,
	RSLT_VAL,
	IMG_FILE_NM,
	INSP_FILE_NM,
	ATTR_1,
	ATTR_2,
	ATTR_N,
	CRT_DT,
	FILE_NM
) VALUES (
	?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTEMP, ?
)